/**
 * Generates the site's cursors, and the CSS tokens that point at them.
 *
 * Run with `npm run cursors` after changing anything below.
 *
 * SCALE is the one number worth touching. It is screen pixels per art pixel,
 * and it decides both readings of "too big": at 2 each art pixel is a 2×2
 * block, which is what makes a cursor look like a game sprite. At 1 the steps
 * are single pixels and the same drawing reads as an ordinary small arrow.
 *
 * Whole numbers only. A fractional scale puts rect edges on half-pixels, and
 * the cursor comes out soft — the one thing this drawing cannot survive.
 *
 * The hotspot is declared in art coordinates and scaled here, so it can never
 * drift out of step with the image the way two hand-edited numbers would.
 */
import { writeFileSync, mkdirSync } from "node:fs";

const SCALE = 2;

// Four inks, traced off the cursor on rishi.design: dark outline, white body,
// and two greys. The greys are what make it read as a drawing rather than a
// silhouette — `l` is the soft edge the light catches, `s` the shadow under it.
// X stays on this site's ink rather than the traced #1b2632; the two are within
// two units of each other and the token keeps the cursor in the page's palette.
const INK = { X: "#1b2431", O: "#ffffff", l: "#cccccc", s: "#9d9d9d" };

const CURSORS = {
  arrow: {
    // The point of the arrow, which is where a click actually lands. The tip
    // sits one art pixel in from the left edge, so this is not 0 0.
    hotspot: [1.5, 0],
    fallback: "default",
    rows: [
      ".XX.........",
      "XOOXX.......",
      "XOOOOXX.....",
      "XlOOOOOXX...",
      "XlOOOOOOOXX.",
      "XllOOOOOOOOX",
      ".XlOOOOOOOsX",
      ".XllOOOOOssX",
      "..XlOOOOOOsX",
      "..XllOOlOOOX",
      "...XlOsllOOX",
      "...XlsslllsX",
      "....XssXllsX",
      "....XsX.XlsX",
      ".....X...XX.",
    ],
  },
  hand: {
    // The tip of the pointing finger, which is the tall left prong.
    hotspot: [1.5, 0],
    fallback: "pointer",
    rows: [
      ".XX...........",
      "XOOX...XXX....",
      "XOOOX.XOOOX...",
      "XlOOOXOOOOOX..",
      "XllOOOOOOOOOX.",
      "XlllOOOOOOOOX.",
      ".XlllOOOOOOOOX",
      "..XOOOOOOOOOOX",
      "..XOOOOOOOOOsX",
      "..XssssslOOssX",
      "..XsssssllsssX",
      "..XsssssllssX.",
      "...XXXXXXlsX..",
      ".........XX...",
    ],
  },
};

/** Merges horizontal runs of one colour into a single rect. */
function svg(rows) {
  const w = rows[0].length * SCALE;
  const h = rows.length * SCALE;
  const parts = [];

  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === ".") { x++; continue; }
      let run = 1;
      while (x + run < row.length && row[x + run] === ch) run++;
      parts.push(
        `<rect x="${x * SCALE}" y="${y * SCALE}" width="${run * SCALE}" height="${SCALE}" fill="${INK[ch]}"/>`,
      );
      x += run;
    }
  });

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges">${parts.join("")}</svg>\n`;
}

mkdirSync(new URL("../public/cursors/", import.meta.url), { recursive: true });

const tokens = [];

for (const [name, def] of Object.entries(CURSORS)) {
  const out = svg(def.rows);
  writeFileSync(new URL(`../public/cursors/${name}.svg`, import.meta.url), out);

  const [hx, hy] = def.hotspot.map((n) => Math.round(n * SCALE));
  tokens.push(`  --cursor-${name}: url("/cursors/${name}.svg") ${hx} ${hy}, ${def.fallback};`);

  const w = def.rows[0].length * SCALE;
  const h = def.rows.length * SCALE;
  console.log(`${name}.svg  ${w}×${h}  hotspot ${hx} ${hy}  ${out.length} bytes`);
  if (w > 32 || h > 32) console.warn(`  ! larger than 32×32; some browsers will ignore it`);
}

writeFileSync(
  new URL("../src/styles/cursors.css", import.meta.url),
  `/* Generated by tools/make-cursors.mjs — do not edit. Run \`npm run cursors\`. */\n:root {\n${tokens.join("\n")}\n}\n`,
);

console.log("wrote src/styles/cursors.css");
